language: python
python:
  - "2.7"
# command to install dependencies
install:
  - npm i npm@latest -g
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
#   # command to run tests
script:
  - make assets
  - ./runtests.sh
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
